%w(vagrant-berkshelf vagrant-vbguest vagrant-omnibus).each do |plugin|
  Vagrant.require_plugin(plugin)
end

Vagrant.configure('2') do |config|
  config.omnibus.chef_version = :latest
  config.vm.box = "debian-7.4.0-amd64_virtualbox"
  config.vm.box_url = "https://s3-eu-west-1.amazonaws.com/ffuenf-vagrant-boxes/debian/debian-7.4.0-amd64_virtualbox.box"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 1024]
  end
  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "./chef/Berksfile"

  config.vm.network :private_network, :ip => "192.168.12.69", :netmask => "255.255.255.0"
  config.vm.synced_folder "/Volumes/Marco/code/", "/home/vagrant/code", :nfs => true
  config.ssh.forward_agent = true

  config.vm.network :forwarded_port, :guest => 3000, :host => 3000 # Rails
  config.vm.network :forwarded_port, :guest => 4567, :host => 4567 # Sinatras
  config.vm.network :forwarded_port, :guest => 5901, :host => 5901 # vnc

  config.vm.provision :chef_solo do |chef|
    chef.nfs = true

    chef.add_recipe('ruby_build')
    chef.add_recipe("git")
    chef.add_recipe("ntp")
    chef.add_recipe("build-essential")
    chef.add_recipe("postgresql")
    chef.add_recipe("mongodb-10gen")
    chef.add_recipe("redis2")
    chef.add_recipe("memcached")
    chef.add_recipe("rabbitmq")
    chef.add_recipe("rbenv")
  end
end
