%w(vagrant-berkshelf vagrant-vbguest vagrant-omnibus).each do |plugin|
  Vagrant.require_plugin(plugin)
end

Vagrant.configure('2') do |config|
  config.omnibus.chef_version = :latest
  config.vm.box = "debian-7.4.0-amd64_virtualbox"
  config.vm.box_url = "https://dl.dropboxusercontent.com/u/8398/vagrant-boxes/debian/7/amd64/debian-7.4.0-amd64_virtualbox.box"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 1024]
  end
  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = "./chef/Berksfile"

  config.vm.network :private_network, :ip => "192.168.12.69", :netmask => "255.255.255.0"
  config.vm.synced_folder "/Volumes/Marco/code/", "/home/vagrant/code", :nfs => true
  config.ssh.forward_agent = true

  config.vm.network :forwarded_port, :guest => 3000, :host => 3000 # Rails
  config.vm.network :forwarded_port, :guest => 9292, :host => 9292 # Sinatras
  config.vm.network :forwarded_port, :guest => 5901, :host => 5901 # vnc

  config.vm.provision :chef_solo do |chef|
    chef.nfs = true
    chef.roles_path = "./chef/roles"
    chef.data_bags_path = "./chef/data_bags"
    chef.add_role "ruby"
  end
end
