site :opscode

cookbook 'apt'
cookbook 'vim'
cookbook "git"
cookbook "build-essential"
cookbook "postgresql"
cookbook "mongodb-10gen"
cookbook "mongodb"
cookbook 'ruby_build', git: "git://github.com/fnichol/chef-ruby_build"
cookbook 'rbenv',
  :git => 'git://github.com/fnichol/chef-rbenv.git', :branch => 'v0.7.2'
